In [39]:
import pandas as pd

In [40]:
import numpy as np

In [41]:
df=pd.read_csv("Uber_Eats_data.csv")

In [42]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

In [43]:
df.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  object
 1   online_order                 23193 non-null  object
 2   book_table                   23193 non-null  object
 3   rate                         23193 non-null  object
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  object
 6   location                     23193 non-null  object
 7   rest_type                    23193 non-null  object
 8   dish_liked                   23193 non-null  object
 9   cuisines                     23193 non-null  object
 10  approx_cost(for two people)  23193 non-null  object
 11  listed_in(type)              23193 non-null  object
 12  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.3+ MB

In [45]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [46]:
#name
df['name'] = df['name'].str.strip().str.title()

In [47]:
#online order
df['online_order'] = df['online_order'].str.strip().str.lower()
df['online_order'] = df['online_order'].map({'yes': 1, 'no': 0})

In [48]:
#book_table
df['book_table'] = df['book_table'].str.strip().str.lower()
df['book_table'] = df['book_table'].map({'yes': 1, 'no': 0})

In [49]:
#votes
df['votes'] = pd.to_numeric(df['votes'], errors='coerce').fillna(0).astype(int)

In [50]:
#location
df['location'] = df['location'].str.strip().str.title()

In [51]:
df['approx_cost(for two people)'] = (
    df['approx_cost(for two people)']
    .astype(str)
    .str.replace(',', '', regex=False)
)

df['approx_cost(for two people)'] = pd.to_numeric(
    df['approx_cost(for two people)'],
    errors='coerce'
)

In [52]:
df['listed_in(type)'] = df['listed_in(type)'].str.strip().str.title()

In [53]:
df.duplicated().sum()

np.int64(35)

In [54]:
df['rate'] = df['rate'].astype(str)

df['rate'] = df['rate'].replace(['NEW', '-', 'nan'], np.nan)

df['rate'] = df['rate'].str.split('/').str[0]

df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

In [55]:
df = df.drop_duplicates().reset_index(drop=True)

In [56]:
df['rest_type'] = df['rest_type'].astype(str)

df['rest_type_primary'] = df['rest_type'].str.split(',').str[0].str.strip()

In [57]:
df['cuisines'] = (
    df['cuisines']
    .astype(str)
    .str.strip()
    .str.replace(r'\s*,\s*', ', ', regex=True)
)

In [58]:
unique_cuisines = (
    df['cuisines']
    .dropna()
    .str.split(', ')
    .explode()
    .unique()
)

In [59]:
unique_cuisines_list = unique_cuisines.tolist()

In [60]:
len(unique_cuisines_list)

98

In [61]:
sorted(unique_cuisines_list)[:10]

['Afghan',
 'Afghani',
 'African',
 'American',
 'Andhra',
 'Arabian',
 'Asian',
 'Assamese',
 'Awadhi',
 'BBQ']

In [62]:
cuisine_temp = (
    df[['name', 'cuisines']]
    .dropna(subset=['cuisines'])
    .assign(cuisine=df['cuisines'].str.split(', '))
    .explode('cuisine')
)

In [63]:
cuisine_counts = (
    cuisine_temp
    .groupby('cuisine')['name']
    .nunique()
    .reset_index(name='restaurant_count')
)

In [64]:
most_represented_cuisine = cuisine_counts.sort_values(
    by='restaurant_count',
    ascending=False
).head(1)

In [65]:
most_represented_cuisine

         cuisine  restaurant_count
68  North Indian              1542

In [66]:
cuisine_counts.sort_values(
    by='restaurant_count',
    ascending=False
).head(10)

         cuisine  restaurant_count
68  North Indian              1542
26       Chinese              1160
28   Continental               537
84  South Indian               527
31     Fast Food               424
16       Biryani               408
22          Cafe               348
44       Italian               321
14     Beverages               280
29      Desserts               275

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23158 entries, 0 to 23157
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23158 non-null  object
 1   online_order                 23158 non-null  int64
 2   book_table                   23158 non-null  int64
 3   rate                         23012 non-null  float64
 4   votes                        23158 non-null  int64
 5   phone                        23158 non-null  object
 6   location                     23158 non-null  object
 7   rest_type                    23158 non-null  object
 8   dish_liked                   23158 non-null  object
 9   cuisines                     23158 non-null  object
 10  approx_cost(for two people)  23158 non-null  int64
 11  listed_in(type)              23158 non-null  object
 12  listed_in(city)              23158 non-null  object
 13  rest_type_primary            23158 non-null  object
dtypes: float64(1), int64(4), object(9)
memory usage: 2.5+ MB

In [68]:
df.duplicated().sum()

np.int64(0)

In [69]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)',
       'rest_type_primary'],
      dtype='object')

In [70]:
df.isna().sum()

name                             0
online_order                     0
book_table                       0
rate                           146
votes                            0
phone                            0
location                         0
rest_type                        0
dish_liked                       0
cuisines                         0
approx_cost(for two people)      0
listed_in(type)                  0
listed_in(city)                  0
rest_type_primary                0
dtype: int64

In [71]:
df.isna().values.any()

np.True_

In [72]:
df['rate'].isna().sum()

np.int64(146)

In [73]:
df['rate'].value_counts().head(10)

rate
3.9    3233
4.0    2857
4.1    2782
3.8    2472
4.2    2095
4.3    1666
3.7    1638
4.4    1115
3.6     875
4.5     627
Name: count, dtype: int64

In [74]:
df.head(3)

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city),rest_type_primary
0,Jalsa,1,1,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Casual Dining
1,Spice Elephant,1,0,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,Casual Dining
2,San Churro Cafe,1,0,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,Cafe

In [76]:
df['rate'].isnull().sum()

np.int64(146)

In [77]:
df = df.dropna(subset=['rate'])

In [78]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city),rest_type_primary
0,Jalsa,1,1,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Casual Dining
1,Spice Elephant,1,0,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,Casual Dining
2,San Churro Cafe,1,0,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,Cafe
3,Addhuri Udupi Bhojana,0,0,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,Quick Bites
4,Grand Village,0,0,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,Casual Dining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23153,Izakaya Gastro Pub,1,1,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs And Bars,Whitefield,Bar
23154,M Bar - Bengaluru Marriott Hotel Whitefield,0,0,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs And Bars,Whitefield,Fine Dining
23155,Keys Cafe - Keys Hotel,0,0,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs And Bars,Whitefield,Casual Dining
23156,Bhagini,0,0,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs And Bars,Whitefield,Casual Dining
23157,Chime - Sheraton Grand Bengaluru Whitefield Ho...,0,1,4.3,236,080 49652769,"Itpl Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs And Bars,Whitefield,Bar

In [79]:
df['rate'].isnull().sum()

np.int64(0)

In [80]:
df.groupby('location')

In [82]:
location_rating = (
    df
    .groupby('location')
    .agg(
        restaurant_count=('name', 'nunique'),
        avg_rating=('rate', 'mean')
    )
    .reset_index()
)
location_rating

              location  restaurant_count  avg_rating
0         Banashankari               100    3.813437
1            Banaswadi                58    3.641026
2    Bannerghatta Road               128    3.682258
3         Basavanagudi                80    3.836713
4   Basaveshwara Nagar                30    3.823944
..                 ...               ...         ...
83      West Bangalore                 1    3.300000
84          Whitefield               293    3.818149
85       Wilson Garden                 6    3.817073
86           Yelahanka                 1    3.900000
87         Yeshwantpur                13    3.775000

[88 rows x 3 columns]

In [85]:
df['votes']

0        775
1        787
2        918
3         88
4        166
        ...
23153    128
23154     77
23155    161
23156     81
23157    236
Name: votes, Length: 23012, dtype: int64

In [87]:
top_rated_hotel = df.loc[df['votes'].idxmax()]

In [88]:
top_rated_hotel[['name', 'location', 'votes', 'rate']]

name        Byg Brewski Brewing Company
location                  Sarjapur Road
votes                             16832
rate                                4.9
Name: 22197, dtype: object

In [89]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city),rest_type_primary
0,Jalsa,1,1,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,Casual Dining
1,Spice Elephant,1,0,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,Casual Dining
2,San Churro Cafe,1,0,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,Cafe
3,Addhuri Udupi Bhojana,0,0,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,Quick Bites
4,Grand Village,0,0,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,Casual Dining
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23153,Izakaya Gastro Pub,1,1,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200,Pubs And Bars,Whitefield,Bar
23154,M Bar - Bengaluru Marriott Hotel Whitefield,0,0,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000,Pubs And Bars,Whitefield,Fine Dining
23155,Keys Cafe - Keys Hotel,0,0,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200,Pubs And Bars,Whitefield,Casual Dining
23156,Bhagini,0,0,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs And Bars,Whitefield,Casual Dining
23157,Chime - Sheraton Grand Bengaluru Whitefield Ho...,0,1,4.3,236,080 49652769,"Itpl Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500,Pubs And Bars,Whitefield,Bar

In [92]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)',
       'rest_type_primary'],
      dtype='object')

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23012 entries, 0 to 23157
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23012 non-null  object
 1   online_order                 23012 non-null  int64
 2   book_table                   23012 non-null  int64
 3   rate                         23012 non-null  float64
 4   votes                        23012 non-null  int64
 5   phone                        23012 non-null  object
 6   location                     23012 non-null  object
 7   rest_type                    23012 non-null  object
 8   dish_liked                   23012 non-null  object
 9   cuisines                     23012 non-null  object
 10  approx_cost(for two people)  23012 non-null  int64
 11  listed_in(type)              23012 non-null  object
 12  listed_in(city)              23012 non-null  object
 13  rest_type_primary            23012 non-null  object
dtypes: float64(1), int64(4), object(9)
memory usage: 3.1+ MB

In [94]:
df = df.rename(columns={
    'approx_cost(for two people)': 'approx_cost_for_two_people',
    'listed_in(type)': 'listed_in_type',
    'listed_in(city)': 'listed_in_city'
})

In [95]:
df.to_csv(
    'uber_29.4.2026.csv',
    index=False
)